local mark = require("harpoon.mark")
local ui = require("harpoon.ui")
local keymap = vim.keymap

keymap.set("n", "<leader>a", mark.add_file)
keymap.set("n", "<A-e>", ui.toggle_quick_menu)
keymap.set("n", "<A-1>", function()
	ui.nav_file(1)
end)
keymap.set("n", "<A-2>", function()
	ui.nav_file(2)
end)
keymap.set("n", "<A-3>", function()
	ui.nav_file(3)
end)
keymap.set("n", "<A-4>", function()
	ui.nav_file(4)
end)
keymap.set("n", "<A-5>", function()
	ui.nav_file(5)
end)
keymap.set("n", "<A-6>", function()
	ui.nav_file(6)
end)
keymap.set("n", "<A-7>", function()
	ui.nav_file(7)
end)
keymap.set("n", "<A-8>", function()
	ui.nav_file(8)
end)
keymap.set("n", "<A-9>", function()
	ui.nav_file(9)
end)
